// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopBackend.Data;

#nullable disable

namespace ShopBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251127060641_Seed-Product-List")]
    partial class SeedProductList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShopBackend.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("SpecialTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Категория 1",
                            Description = "Забывать обуславливает повседневной отметить занимаемых воздействия образом мира работы гражданского.",
                            Image = "https://placehold.co/200",
                            Name = "Невероятный Хлопковый Портмоне",
                            Price = 197.33000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Категория 2",
                            Description = "Таким рост последовательного.",
                            Image = "https://placehold.co/200",
                            Name = "Эргономичный Меховой Кошелек",
                            Price = 81.719999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Категория 2",
                            Description = "В инновационный и от показывает дальнейших задач различных постоянное особенности.",
                            Image = "https://placehold.co/200",
                            Name = "Фантастический Бетонный Берет",
                            Price = 158.41999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Категория 1",
                            Description = "Рост широким идейные значение участниками играет.",
                            Image = "https://placehold.co/200",
                            Name = "Свободный Гранитный Плащ",
                            Price = 115.56999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Категория 1",
                            Description = "Массового высшего кадровой показывает.",
                            Image = "https://placehold.co/200",
                            Name = "Невероятный Гранитный Плащ",
                            Price = 852.90999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Категория 3",
                            Description = "Нашей обуславливает проверки разработке.",
                            Image = "https://placehold.co/200",
                            Name = "Великолепный Кожанный Ножницы",
                            Price = 831.41999999999996,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Категория 2",
                            Description = "Подготовке за что.",
                            Image = "https://placehold.co/200",
                            Name = "Практичный Хлопковый Клатч",
                            Price = 474.62,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Категория 2",
                            Description = "Нас предложений зависит системы существующий воздействия на путь очевидна.",
                            Image = "https://placehold.co/200",
                            Name = "Эргономичный Стальной Стул",
                            Price = 369.63,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Категория 3",
                            Description = "Разнообразный опыт а повседневной широким для модернизации кадров предложений.",
                            Image = "https://placehold.co/200",
                            Name = "Потрясающий Неодимовый Кошелек",
                            Price = 934.84000000000003,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Категория 2",
                            Description = "Ресурсосберегающих актуальность выполнять дальнейших начало.",
                            Image = "https://placehold.co/200",
                            Name = "Великолепный Стальной Кулон",
                            Price = 861.64999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Категория 2",
                            Description = "Инновационный постоянный систему направлений создаёт отметить административных курс очевидна ресурсосберегающих.",
                            Image = "https://placehold.co/200",
                            Name = "Большой Натуральный Куртка",
                            Price = 547.37,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Категория 1",
                            Description = "Воздействия развития укрепления сущности внедрения играет равным.",
                            Image = "https://placehold.co/200",
                            Name = "Интеллектуальный Натуральный Ремень",
                            Price = 331.50999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Категория 3",
                            Description = "Поэтапного прежде широкому.",
                            Image = "https://placehold.co/200",
                            Name = "Большой Неодимовый Автомобиль",
                            Price = 36.950000000000003,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Категория 2",
                            Description = "Материально-технической внедрения форм рост следует позиции прогрессивного модель правительством подготовке.",
                            Image = "https://placehold.co/200",
                            Name = "Невероятный Пластиковый Сабо",
                            Price = 138.68000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Категория 2",
                            Description = "Принимаемых кругу курс работы.",
                            Image = "https://placehold.co/200",
                            Name = "Грубый Гранитный Компьютер",
                            Price = 880.61000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Категория 1",
                            Description = "Начало создание нами структуры понимание системы дальнейших сложившаяся в национальный.",
                            Image = "https://placehold.co/200",
                            Name = "Потрясающий Хлопковый Носки",
                            Price = 850.22000000000003,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Категория 3",
                            Description = "Равным специалистов также актуальность.",
                            Image = "https://placehold.co/200",
                            Name = "Лоснящийся Пластиковый Ремень",
                            Price = 541.5,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Категория 1",
                            Description = "Представляет организации специалистов равным управление важную рост дальнейшее предпосылки.",
                            Image = "https://placehold.co/200",
                            Name = "Практичный Пластиковый Майка",
                            Price = 847.76999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Категория 1",
                            Description = "Консультация задания сознания организационной.",
                            Image = "https://placehold.co/200",
                            Name = "Практичный Деревянный Сабо",
                            Price = 178.22,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Категория 1",
                            Description = "Работы формированию следует системы активом.",
                            Image = "https://placehold.co/200",
                            Name = "Маленький Резиновый Автомобиль",
                            Price = 184.43000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Категория 1",
                            Description = "Технологий представляет нас новая.",
                            Image = "https://placehold.co/200",
                            Name = "Практичный Кожанный Кепка",
                            Price = 390.60000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Категория 2",
                            Description = "Проблем понимание таким повседневная внедрения модели.",
                            Image = "https://placehold.co/200",
                            Name = "Маленький Бетонный Кепка",
                            Price = 341.81,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Категория 1",
                            Description = "Намеченных материально-технической формированию значимость собой реализация изменений нами общественной структура.",
                            Image = "https://placehold.co/200",
                            Name = "Интеллектуальный Хлопковый Плащ",
                            Price = 919.73000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Категория 1",
                            Description = "Повышению сознания образом социально-ориентированный сущности ресурсосберегающих.",
                            Image = "https://placehold.co/200",
                            Name = "Большой Неодимовый Куртка",
                            Price = 746.48000000000002,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Категория 2",
                            Description = "Сложившаяся начало занимаемых правительством.",
                            Image = "https://placehold.co/200",
                            Name = "Потрясающий Неодимовый Автомобиль",
                            Price = 845.23000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Категория 3",
                            Description = "Задания сомнений сознания по материально-технической мира.",
                            Image = "https://placehold.co/200",
                            Name = "Грубый Натуральный Кулон",
                            Price = 942.23000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Категория 3",
                            Description = "Образом особенности отметить национальный интересный.",
                            Image = "https://placehold.co/200",
                            Name = "Практичный Резиновый Автомобиль",
                            Price = 941.11000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Категория 3",
                            Description = "И требует этих внедрения деятельности позволяет.",
                            Image = "https://placehold.co/200",
                            Name = "Потрясающий Стальной Куртка",
                            Price = 484.38,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Категория 3",
                            Description = "Значение новая рост задач модели зависит кадровой социально-экономическое определения всего.",
                            Image = "https://placehold.co/200",
                            Name = "Великолепный Натуральный Сабо",
                            Price = 308.85000000000002,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Категория 2",
                            Description = "Очевидна высокотехнологичная кадров настолько соображения актуальность играет рост постоянное представляет.",
                            Image = "https://placehold.co/200",
                            Name = "Интеллектуальный Гранитный Стул",
                            Price = 304.32999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Категория 2",
                            Description = "Стороны кадров участниками демократической с таким также что.",
                            Image = "https://placehold.co/200",
                            Name = "Лоснящийся Резиновый Компьютер",
                            Price = 524.62,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Категория 3",
                            Description = "Информационно-пропогандистское реализация степени влечёт подготовке административных требует укрепления.",
                            Image = "https://placehold.co/200",
                            Name = "Интеллектуальный Меховой Свитер",
                            Price = 688.86000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Категория 1",
                            Description = "Другой позволяет сфера играет дальнейших рост проверки с.",
                            Image = "https://placehold.co/200",
                            Name = "Грубый Стальной Плащ",
                            Price = 540.35000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Категория 3",
                            Description = "Постоянное прогресса работы задания разработке консультация.",
                            Image = "https://placehold.co/200",
                            Name = "Грубый Гранитный Берет",
                            Price = 424.73000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Категория 2",
                            Description = "Начало разработке активизации шагов.",
                            Image = "https://placehold.co/200",
                            Name = "Лоснящийся Деревянный Ножницы",
                            Price = 53.880000000000003,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Категория 1",
                            Description = "Проверки по интересный рамки массового широким настолько широким кадровой что.",
                            Image = "https://placehold.co/200",
                            Name = "Великолепный Резиновый Компьютер",
                            Price = 89.819999999999993,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Категория 3",
                            Description = "Определения что богатый систему забывать обеспечивает социально-ориентированный.",
                            Image = "https://placehold.co/200",
                            Name = "Свободный Бетонный Автомобиль",
                            Price = 187.78,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Категория 3",
                            Description = "Современного поставленных значение постоянный насущным материально-технической идейные эксперимент качества место.",
                            Image = "https://placehold.co/200",
                            Name = "Грубый Неодимовый Ремень",
                            Price = 97.180000000000007,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Категория 2",
                            Description = "Создаёт проект кадровой консультация национальный настолько интересный вызывает предпосылки.",
                            Image = "https://placehold.co/200",
                            Name = "Эргономичный Резиновый Автомобиль",
                            Price = 857.83000000000004,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Категория 2",
                            Description = "Инновационный интересный технологий.",
                            Image = "https://placehold.co/200",
                            Name = "Грубый Гранитный Портмоне",
                            Price = 468.06999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Категория 2",
                            Description = "Оценить работы подготовке информационно-пропогандистское уровня новая зависит.",
                            Image = "https://placehold.co/200",
                            Name = "Свободный Пластиковый Майка",
                            Price = 236.59,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Категория 1",
                            Description = "Эксперимент организации воздействия мира поэтапного кругу правительством.",
                            Image = "https://placehold.co/200",
                            Name = "Большой Бетонный Ботинок",
                            Price = 157.56999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Категория 2",
                            Description = "Сомнений соображения предпосылки инновационный.",
                            Image = "https://placehold.co/200",
                            Name = "Грубый Хлопковый Автомобиль",
                            Price = 236.09,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Категория 2",
                            Description = "Массового разработке формировании.",
                            Image = "https://placehold.co/200",
                            Name = "Интеллектуальный Гранитный Кулон",
                            Price = 133.5,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Категория 2",
                            Description = "Повышение анализа структура позиции рост.",
                            Image = "https://placehold.co/200",
                            Name = "Невероятный Гранитный Ножницы",
                            Price = 797.38999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Категория 1",
                            Description = "Инновационный базы важную инновационный различных нашей.",
                            Image = "https://placehold.co/200",
                            Name = "Интеллектуальный Пластиковый Стол",
                            Price = 542.71000000000004,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Категория 3",
                            Description = "Разнообразный ресурсосберегающих прежде сомнений богатый высшего обеспечение.",
                            Image = "https://placehold.co/200",
                            Name = "Интеллектуальный Меховой Кепка",
                            Price = 44.619999999999997,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Категория 2",
                            Description = "Повседневной сложившаяся обеспечение профессионального.",
                            Image = "https://placehold.co/200",
                            Name = "Большой Неодимовый Ботинок",
                            Price = 560.04999999999995,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Категория 2",
                            Description = "Также широким кадровой анализа.",
                            Image = "https://placehold.co/200",
                            Name = "Фантастический Меховой Портмоне",
                            Price = 572.32000000000005,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Категория 1",
                            Description = "Сущности структура зависит курс.",
                            Image = "https://placehold.co/200",
                            Name = "Лоснящийся Резиновый Клатч",
                            Price = 329.41000000000003,
                            SpecialTag = "Популярный"
                        });
                });

            modelBuilder.Entity("ShopBackend.Model.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
